# Generated by Django 4.1.1 on 2022-10-09 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('postition', models.CharField(max_length=6)),
                ('hire_date', models.DateTimeField()),
                ('country', models.CharField(max_length=7)),
                ('recidence_city', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=10)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.CharField(db_collation='big5_chinese_ci', max_length=45)),
                ('banck_account', models.IntegerField()),
                ('passport_data', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('car_right_photo', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(max_length=250, null=True, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('rating', models.IntegerField(default=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
