# Generated by Django 4.1.1 on 2022-10-29 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('date_of_issue', models.DateField()),
                ('date_of_completion', models.DateField()),
                ('series_number', models.CharField(max_length=9, unique=True)),
                ('lic_photo', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'driving_licence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('postition', models.CharField(max_length=14)),
                ('hire_date', models.DateTimeField()),
                ('recidence_city', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=17)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('banck_account', models.CharField(max_length=254, unique=True)),
                ('passport_data', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('photo', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('rating', models.IntegerField(default=100)),
                ('is_staff', models.IntegerField(default=False)),
                ('is_active', models.IntegerField(default=True)),
                ('is_superuser', models.IntegerField(default=False)),
                ('is_allowed_orders', models.IntegerField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('driving_licence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.drivinglicence')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, null=True)),
                ('rate', models.FloatField()),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
                'managed': True,
                'unique_together': {('id', 'user', 'car')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=9)),
                ('date_creation', models.DateTimeField()),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'managed': True,
                'unique_together': {('id', 'user', 'car')},
            },
        ),
        migrations.CreateModel(
            name='Maintain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_maintain', models.DateTimeField()),
                ('address', models.CharField(max_length=45)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car.car')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.employee')),
            ],
            options={
                'db_table': 'maintain',
                'managed': True,
                'unique_together': {('id', 'employee', 'car')},
            },
        ),
    ]
