# Generated by Django 4.1.1 on 2022-10-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='driving_licence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='car.drivinglicence'),
        ),
    ]
