# Generated by Django 4.1.1 on 2022-10-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicence',
            name='date_of_completion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='drivinglicence',
            name='date_of_issue',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='drivinglicence',
            name='is_valid',
            field=models.IntegerField(default=False),
        ),
    ]
