# Generated by Django 4.1.1 on 2022-10-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_maintain', models.DateTimeField()),
                ('address', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'maintain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=9)),
                ('date_creation', models.DateTimeField()),
                ('date_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, null=True)),
                ('rate', models.FloatField()),
                ('published', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
