# Generated by Django 4.1.1 on 2022-12-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_order_order_price_alter_order_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
    ]
