# Generated by Django 4.1.1 on 2022-12-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lic_serial',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
