# Generated by Django 4.1.1 on 2022-12-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_lic_serial_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
