# Generated by Django 4.1.1 on 2022-12-18 14:36

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lic_photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload),
        ),
    ]
