# Generated by Django 4.1.1 on 2022-12-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_money_alter_customuser_lic_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lic_serial',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
