# Generated by Django 4.1.1 on 2022-12-19 14:00

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customuser_lic_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lic_photo',
            field=models.ImageField(blank=True, default='../../media/NoPhoto.jpg', null=True, upload_to=user.models.upload),
        ),
    ]
