# Generated by Django 4.1.1 on 2022-10-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=45)),
                ('photo', models.CharField(blank=True, max_length=45, null=True)),
                ('registration_number', models.CharField(max_length=8)),
                ('vin_code', models.CharField(max_length=45)),
                ('insure_number', models.IntegerField()),
                ('maker', models.CharField(max_length=3)),
                ('year_registration', models.DateField()),
                ('status', models.CharField(max_length=3)),
                ('num_of_sits', models.IntegerField()),
                ('fuel_tank', models.FloatField()),
                ('price_per_min', models.FloatField()),
                ('available_now', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryCar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'category_car',
                'managed': False,
            },
        ),
    ]
