# Generated by Django 4.1.1 on 2022-10-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('passenger car', 'passenger car'), ('sedan', 'sedan'), ('coupe', 'coupe'), ('hatch-back', 'hatch-back'), ('hybrid', 'hybrid'), ('minivan', 'minivan'), ('suv', 'suv'), ('convertible', 'convertible'), ('sports car', 'sports car')], max_length=50)),
            ],
            options={
                'db_table': 'category_car',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('class_field', models.CharField(db_column='class', max_length=10)),
                ('vin_code', models.CharField(max_length=17, unique=True)),
                ('registration_number', models.CharField(max_length=8, unique=True)),
                ('insure_number', models.CharField(max_length=13, unique=True)),
                ('year', models.TextField()),
                ('number_of_seats', models.IntegerField(db_column='number of seats')),
                ('fuel_tank_left', models.FloatField(default=0)),
                ('price_per_min', models.FloatField(default=0)),
                ('available_now', models.IntegerField(default=0)),
                ('photo', models.CharField(blank=True, max_length=45, null=True)),
                ('category_cars', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car.categorycar')),
            ],
            options={
                'db_table': 'car',
                'managed': True,
            },
        ),
    ]
