# Generated by Django 4.1.1 on 2022-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.IntegerField(default=False),
        ),
    ]
