# Generated by Django 4.1.1 on 2022-11-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
