# Generated by Django 4.1.1 on 2022-12-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_latitude_car_longitude_alter_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
